import Home_header from "modules/home_header.tsx";
import Intro from "modules/intro.tsx";
import Head from "next/head";
import $ from "jquery";

export default function Home() {
  if (typeof window !== "undefined") {
    // browser code
    $(".main_page").on("scroll", function () {
      console.log($(".main_page").scrollTop());
      if ($(".main_page").scrollTop() > 1000) {
        $(".main_body").addClass("make_white");
      } else {
        $(".main_body").removeClass("make_white");
      }
    });
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
          crossorigin="anonymous"
        ></script>

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=PT+Sans&family=Poppins:wght@300;400;500;600&family=Roboto:wght@100;400;900&display=swap"
          rel="stylesheet"
        />
        <script
          src="https://kit.fontawesome.com/4ea6e3ab0b.js"
          crossorigin="anonymous"
        ></script>

        <script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
        <script src="http://threejs.org/examples/js/libs/stats.min.js"></script>
      </Head>
      <div id="particles-js" className="main_body">
        <div className="main_page">
          <Home_header />
          <Intro />
        </div>
      </div>
    </>
  );
}
